//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCertificacion
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Servicios = new HashSet<Servicio>();
        }

        [ScaffoldColumn(false)]
        public int idempresa { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(50)]
        [Display(Name = "Empresa")]
        public string nombre { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "El teléfono es requerido"), MaxLength(20)]
        [Display(Name = "Teléfono")]
        public string telefono { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La ciudad es requerida"), MaxLength(25)]
        [Display(Name = "Ciudad")]
        public string ciudad { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La dirección es requerida"), MaxLength(100)]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }
        public Nullable<int> idusuario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Servicio> Servicios { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
